version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    container_name: eonext-base-dev

volumes:
  bundle:
