defaults: &defaults
  applications:
    client_id: <%= ENV['EVEONLINE_CLIENT_ID'] %>
    client_secret: <%= ENV['EVEONLINE_CLIENT_SECRET'] %>
    esi_base: <%= ENV['EVEONLINE_ESI_BASE'] %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
